export const RegionToAPI: Record<string, string> = {
  '서울': 'SEOUL',
  '부산': 'BUSAN',
  '대구': 'DAEGU',
  '인천': 'INCHEON',
  '광주': 'GWANGJU',
  '대전': 'DAEJEON',
  '울산': 'ULSAN',
  '세종': 'SEJONG',
  '경기': 'GYEONGGI',
  '강원': 'GANGWON',
  '충북': 'CHUNGBUK',
  '충남': 'CHUNGNAM',
  '전북': 'JEONBUK',
  '전남': 'JEONNAM',
  '경북': 'GYEONGBUK',
  '경남': 'GYEONGNAM',
  '제주': 'JEJU',
};

export const RelatedInstitutionToAPI: Record<string, string> = {
  '고용노동부': 'EMPLOYMENT_LABOR',
  '과기부': 'SCIENCE_TECH',
  '과학기술정보통신부': 'SCIENCE_TECH',
  '농림축산식품부': 'AGRICULTURE',
  '산업통상자원부': 'INDUSTRY_TRADE',
  '중소벤처기업부': 'SME_STARTUPS',
  '중기부': 'SME_STARTUPS',
  '해양수산부': 'OCEAN_FISHERIES',
  '국토교통부': 'LAND_TRANSPORT',
  '금융기관': 'FINANCIAL_INSTITUTION',
  '그 외 기관': 'OTHER',
};

export const IndustryTypeToAPI: Record<string, string> = {
  '제조업': 'MANUFACTURING',
  '도소매업': 'WHOLESALE_RETAIL',
  '도매 및 소매업': 'WHOLESALE_RETAIL',
  '숙박 및 음식점업': 'ACCOMMODATION_FOOD',
  '건설업': 'CONSTRUCTION',
  '운수업': 'TRANSPORTATION',
  '운수 및 창고업': 'TRANSPORT_STORAGE',
  '부동산업 및 임대업': 'REAL_ESTATE_RENTAL',
  '부동산업': 'REAL_ESTATE',
  '전문, 과학 및 기술 서비스업': 'PROFESSIONAL_SCIENTIFIC_TECHNICAL',
  '사업시설관리 및 사업지원 서비스업': 'FACILITY_MANAGEMENT_RENTAL',
  '사업시설 관리, 사업 지원 및 임대 서비스업': 'FACILITY_MANAGEMENT_RENTAL',
  '교육 서비스업': 'EDUCATION',
  '보건업 및 사회복지 서비스업': 'HEALTH_SOCIAL_WORK',
  '예술, 스포츠 및 여가관련 서비스업': 'ARTS_SPORTS_RECREATION',
  '협회 및 단체, 수리 및 기타 개인 서비스업': 'ASSOCIATION_REPAIR_OTHER_SERVICES',
  '농업, 임업 및 어업': 'AGRICULTURE_FORESTRY_FISHERIES',
  '광업': 'MINING',
  '전기, 가스, 증기 및 공기 조절 공급업': 'ELECTRICITY_GAS_AIR_CONDITIONING',
  '전기, 가스, 증기 및 수도사업': 'ELECTRICITY_GAS_AIR_CONDITIONING',
  '수도, 하수 및 폐기물 처리, 원료 재생업': 'WATER_WASTE_MANAGEMENT',
  '하수·폐기물 처리, 원료재생 및 환경복원업': 'WATER_WASTE_MANAGEMENT',
  '정보통신업': 'INFORMATION_COMMUNICATION',
  '금융 및 보험업': 'FINANCE_INSURANCE',
  '출판, 영상, 방송통신 및 정보서비스업': 'INFORMATION_COMMUNICATION',
  '공공행정, 국방 및 사회보장 행정': 'PUBLIC_ADMIN_SOCIAL_SECURITY',
  '공공 행정, 국방 및 사회보장 행정': 'PUBLIC_ADMIN_SOCIAL_SECURITY',
  '가구내 고용활동 및 달리 분류되지 않은 자가소비 생산활동': 'HOUSEHOLD_EMPLOYMENT_PRODUCTION',
  '국제 및 외국기관': 'INTERNATIONAL_ORGANIZATION',
};

export const SupportTargetToAPI: Record<string, string> = {
  '소상공인': 'SMALL_BUSINESS_OWNER',
  '소공인': 'SMALL_ENTERPRISE',
  '전통시장': 'TRADITIONAL_MARKET',
  '예비창업자': 'PROSPECTIVE_ENTREPRENEUR',
  '소상공인(폐업)': 'CLOSED_SMALL_BUSINESS_OWNER',
  '기타': 'ETC',
};
